# Generated by Django 4.2.4 on 2023-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='rates',
            field=models.ManyToManyField(to='contents.rating'),
        ),
    ]
