# Generated by Django 4.2.4 on 2023-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_content_rates_rating_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
